
Hooks:PostHook(HUDTeammate, "set_armor", "set_armor_pain_event", function(self, data, ...)
    log("hello there")
    local Value = math.clamp(data.current / data.total, 0, 1)
    local real_value = math.round((data.total * 10) * Value)
    dohttpreq("http://localhost:8001/event/shield/"..real_value, function(data2)
        log("answer ".. data2)
    end)
end)

Hooks:PostHook(HUDTeammate, "set_health", "set_health_pain_event", function(self, data, ...)
    log("hello there")
    local Value = math.clamp(data.current / data.total, 0, 1)
    local real_value = math.round((data.total * 10) * Value)
    dohttpreq("http://localhost:8001/event/health/"..real_value, function(data2)
        log("answer ".. data2)
    end)
end)

Hooks:PostHook(HUDTeammate, "_damage_taken", "damage_taken_pain_event", function(self, ...)
    log("hello there")
    dohttpreq("http://localhost:8001/event/damage_taken/", function(data2)
        log("answer ".. data2)
    end)
end)
